
server:
  port: 8082
#日志相关
logging:
  level:
    com:
      examplexyy:
        demo: debug

  file: /logs/app.log


spring:
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true

  datasource:
    url: jdbc:mysql://localhost:3306/xyy
    username: root
    password: root
    driver-class-nam: com.mysql.jdbc.Driver

  redis:


  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300


#邮件相关
mail:
  transport:
    protocol: 25
    account: 18850198317@163.com
    password: xyy19931101
    host: smtp.163.com
